### ISSUE TITLE
Error: ENOENT: no such file or directory, stat 'E:\udacity\evaluate-news-nlp\src\server\dist\index.html'

### ISSUE THREAD

**Issue by PharaonicDev** [m-ahmedy/evaluate-news-nlp#1]
help me fix that issue

**Comment by m-ahmedy** [comment]
Provide more details about the issue and how to reproduce

**Comment by PharaonicDev** [comment]
clone repo  npm install and webpackes and` npm start ` that error 
ENOENT: no such file or directory, stat 'E:\udacity\evaluate-news-nlp\src\server\dist\index.html'

**Comment by m-ahmedy** [comment]
Not enough to reproduce

Make sure to use the **path** node module to resolve any incorrect paths on your part
